### ISSUE TITLE
Build for SDK 20.08

### ISSUE THREAD

**Issue by gasinvein** [flathub/org.freedesktop.Sdk.Extension.golang#26]
Freedesktop SDK 20.08 is released, please build the extension for it.

**Comment by grdryn** [comment]
Yes please! :slightly_smiling_face: I think the absence of it means that flatpaks built on 20.08 can't make use of it by default (at least I'm guessing this is why it's not showing up in emacs for me now).

**Comment by grdryn** [comment]
I created #27 to do this, and the build job provided an install link that I'm using until there's an update available on flathub.

The other thing that can be done here is to update to Go 1.15, since that's available now too.

@barthalion @jakobjakobson13 is there anything else I can do to help move this along? :slightly_smiling_face:

**Comment by muep** [comment]
> Yes please! slightly_smiling_face I think the absence of it means that flatpaks built on 20.08 can't make use of it by default (at least I'm guessing this is why it's not showing up in emacs for me now).

Hi @grdryn , just in case you wish to share how you are using them in Emacs or have ideas on how to make them simpler to use, feel free to drop a note at https://github.com/flathub/org.gnu.emacs/issues/31
